# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastkafkachat',
                'doc_host': 'https://airtai.github.io',
                'git_url': 'https://github.com/airtai/fastkafkachat',
                'lib_path': 'fastkafkachat'},
  'syms': { 'fastkafkachat.chat_generator': { 'fastkafkachat.chat_generator.GenerateChatRequest': ( 'chat_generator.html#generatechatrequest',
                                                                                                    'fastkafkachat/chat_generator.py'),
                                              'fastkafkachat.chat_generator._get_response_from_model': ( 'chat_generator.html#_get_response_from_model',
                                                                                                         'fastkafkachat/chat_generator.py'),
                                              'fastkafkachat.chat_generator.generate_chat_response': ( 'chat_generator.html#generate_chat_response',
                                                                                                       'fastkafkachat/chat_generator.py')},
            'fastkafkachat.server': { 'fastkafkachat.server.create_fastapi_app': ( 'api_web_service.html#create_fastapi_app',
                                                                                   'fastkafkachat/server.py'),
                                      'fastkafkachat.server.run_webserver': ( 'api_web_service.html#run_webserver',
                                                                              'fastkafkachat/server.py')}}}
